### ISSUE TITLE
Slides: Setting the Stage

### ISSUE THREAD

**Issue by eswan18** [uc-python/advanced-python-datasci#3]
Refresher on Key Python & Pandas Topics

**Comment by eswan18** [comment]
@bradleyboehmke – I forget, is this what "Setting the Stage" is meant to be? Want to clarify before I start building slides. If so, I'll change the issue name to better reflect that.

**Comment by eswan18** [comment]
🤦‍♂️ There's already a notebook for this in the repo, that I made.

I'll plan to update this a little once all of our content is finished, since we can take out Python concepts that don't come up during this workshop. We *will* need to do some renumbering of notebooks later though, if we plan to include this.

**Comment by bradleyboehmke** [comment]
Once we're all done we can decide what needs to be in the Setting the Stage. I think my original intent was for that to be some slides that talk about projects in organizations and how they often include a combination of ML and software engineering skills.  So this would be an opportunity to tie together our material so attendees know why we jump from ML topics to software engineering topics.
