### ISSUE TITLE
Edit Setting the Stage

### ISSUE THREAD

**Issue by eswan18** [uc-python/advanced-python-datasci#32]
Before delivery, we should trim the Setting the Stage notebook to only cover concepts that will come up in the workshop.

**Comment by bradleyboehmke** [comment]
Here are some of the topics that I hit on regularly but just assume the attendee has the knowledge:

- module imports and aliases
- importing data
- subsetting data
   - selecting columns by name or data type
   - dropping columns
- simple aggregation
   - `value_counts()`
   - `describe()` & `mean()`
- f-strings
- visualization
   - pandas plots (histograms, scatter plots)
   - seaborn plots

**Comment by eswan18** [comment]
That's super helpful. If we keep Setting the Stage, I'll try to limit it to primarily these things.

**Comment by bradleyboehmke** [comment]
In the updated agenda we only have this section being 15 min long.  Maybe we just trim the current Setting the Stage content to address some of the assumed knowledge that we take for granted in this course.  So, basically, just hitting on the topics I mentioned above and any others that pop up in your section that would be good to quickly show.  

Thoughts?

**Comment by eswan18** [comment]
I'm on board with that and I can make that change to the notebook later today.

**Comment by eswan18** [comment]
Closed in #48
