### ISSUE TITLE
Fix link to adult census data info

### ISSUE THREAD

**Issue by bradleyboehmke** [uc-python/advanced-python-datasci#53]
Link to online info pertaining to adult census data is broken:

- https://github.com/uc-python/advanced-python-datasci/blob/master/notebooks/02-explore_data.ipynb
- https://github.com/uc-python/advanced-python-datasci/blob/master/notebooks/03-first_model.ipynb

**Comment by M-Barrows** [comment]
The link seems to be working again as of the writing of this comment. 
![image](https://user-images.githubusercontent.com/7907749/149029824-bc145626-5f4d-4f46-ad13-aaf2f1273831.png)

**Comment by bradleyboehmke** [comment]
Interesting; wondering if the site went down for a while. Regardless, makes for an easy fix!
