### ISSUE TITLE
NameError: name 'num_features' is not defined

### ISSUE THREAD

**Issue by M-Barrows** [uc-python/advanced-python-datasci#55]
When working through the [Case Study](https://github.com/uc-python/advanced-python-datasci/blob/master/notebooks/Case%20Study.ipynb), there are two code cells that the user is instructed to "RUN THIS CODE CELL AS-IS". However, unless the user has already created the variables "num_features" and "cat_features", the code will fail. 

It would likely be beneficial to either 

- Create the variables for the user in the first of the two code chunks 
- Instruct the user to create the variables with **exactly those names** earlier in the case study (like in item 4 of Exploratory data Analysis)

**Comment by augustopher** [comment]
Added in 186f436
